// <auto-generated />
namespace ShopTastic.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CheckOut : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CheckOut));
        
        string IMigrationMetadata.Id
        {
            get { return "202008231949399_CheckOut"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
